[package]
name = "shadml_bundler"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
shadml_allocator = { workspace = true }
shadml_diagnostics = { workspace = true }
shadml_parser = { workspace = true }
shadml_semantic = { workspace = true }
shadml_ast_lowering = { workspace = true }
shadml_hir = { workspace = true }
shadml_mir = { workspace = true }
shadml_wgsl_codegen = { workspace = true }
toml = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
